name: Astro

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          check-latest: true

      - name: Install dependencies
        run: pnpm i

      - name: Build for production
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Run typescript check
        run: pnpm tsc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
