name: Astro

on:
  push:

jobs:
  astro:
    name: Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v20

      - name: Install dependencies
        run: nix develop --command pnpm i

      - name: Build for production
        run: nix develop --command pnpm build

      - name: Run lint
        run: nix develop --command pnpm lint

      - name: Run typescript check
        run: nix develop --command pnpm tsc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: astro
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
